### ISSUE TITLE
Videos appearance

### ISSUE THREAD

**Issue by slrslr** [krixano/KxoVid#1]
Hello, i assume KxoVid is in beta and possibly videos not yet appear, because i do not see any videos anywhere when browsing users profiles or homepage http://127.0.0.1:43110/14c5LUN73J7KKMznp9LvZWkxpZFWgE1sDz/?/

**Comment by krixano** [comment]
You must download one of the categories/hubs. Go to the "Categories" page and click download. Only some of the categories/hubs have videos, these are "TV Shows", "Programming", and a few others.

**Comment by slrslr** [comment]
That worked, thank you.

> This was explained in the introduction page when you first visited the zite.

If i missed this, others may also. Maybe if user not downloaded any categories yet, the site should be telling him on the homepage (instead of empty "New Videos" section) the text like: "Go to [Categories](http://127.0.0.1:43110/14c5LUN73J7KKMznp9LvZWkxpZFWgE1sDz/?/categories) page to download categories of videos you like.". This text will appear until user add some categories.

I think user should be able to bulk add categories instead of spending time clicking one category at once and then scrolling for another one. Actualy i would like to have access to all merger sites videos by default. This manual category adding, one by one is not as good as if site would automaticaly add lets say 20 most popular categories on first visit or allow user to bulk add or at least some more quick, condensed way to show & select categories without need of long scrolling and focusing.
